CREATE TABLE projectfiles (line STRING);
LOAD DATA LOCAL INPATH 'episodeIV_dialouges.txt' INTO TABLE projectfiles;
LOAD DATA LOCAL INPATH 'episodeV_dialouges.txt' INTO TABLE projectfiles;
LOAD DATA LOCAL INPATH 'episodeVI_dialouges.txt' INTO TABLE projectfiles;

CREATE TABLE dialouge_count AS
SELECT name, count(1) AS count FROM
(SELECT split(line, '\t')[0] AS name FROM projectfiles) n
GROUP BY n.name
ORDER BY count DESC;