-- Create a table to store results
$ hive> CREATE TABLE files (lines STRING);

-- Load data into the database using a file on your local system (NOT HDFS)
$ hive> LOAD DATA LOCAL INPATH '/root/pigInput.txt' INTO TABLE files;

-- Create a new table using data from the files table
$ hive> CREATE TABLE word_counts AS
      > SELECT word, count(1) AS count FROM
      > (SELECT explode(split(lines, ' ')) AS word FROM files) w
      > GROUP BY word
      > ORDER BY word;